services:
  uptime:
    image: louislam/uptime-kuma:2-slim
    env_file:
      - .env
    volumes:
      - ${DATA_PATH}:/app/data
      - ${DOCKER_SOCK}:/var/run/docker.sock
    x-ports:
      - uptime.domain.com:3001/https
