services:
  docusaurus:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # Copy files from container to be able to modify them:
    # cd ${DATA_PATH}/docusaurus
    # mkdir -v {blog,docs,docusaurus.config.js,sidebars.js,src,static,xfer}
    # cp -rv {blog,docs,docusaurus.config.js,sidebars.js,src,static} xfer/
    volumes:
      - ${DATA_PATH}/docusaurus/docusaurus.config.js:/app/docusaurus.config.js
      - ${DATA_PATH}/docusaurus/sidebars.js:/app/sidebars.js
      - ${DATA_PATH}/docusaurus/blog:/app/blog
      - ${DATA_PATH}/docusaurus/docs:/app/docs
      - ${DATA_PATH}/docusaurus/static:/app/static
      - ${DATA_PATH}/docusaurus/src:/app/src
      - ${DATA_PATH}/docusaurus/xfer:/app/xfer
    x-ports:
      - https://www.domain.com:3000/https
