services:
  actual-budget:
    image: docker.io/actualbudget/actual-server:latest
    env_file:
      - .env
    volumes:
      - ${DATA_PATH}:/data
    user: 3568:3568
    deploy:
      resources:
        limits:
          memory: 1G
    x-ports:
      - budget.domain.com:5006/https
