services:
  semaphore:
    image: semaphoreui/semaphore:latest
    env_file:
      - .env
    volumes:
      - ${DATA_PATH}:/var/lib/semaphore
      - ${CONFIG_PATH}:/etc/semaphore
    x-ports:
      - https://semaphore.domain.com:3000/https
