services:
  vaultwarden:
    image: vaultwarden/server:latest
    env_file:
      - .env
    volumes:
      - ${DATA_PATH}:/data/
    x-ports:
      - vault.domain.co:80/https
    deploy:
      resources:
        limits:
          memory: 1G
